### PR TITLE
Add TA's code

### PR DESCRIPTION
**Pull request by jasonsie1024**
Hey fancy boys and girls, I've been a cute copy cat and copy all the example code from TA.
Hope Ü like them.

### CODE REVIEW

**Review by fywangVick — COMMENTED** [review]
HUMOROUS!

**Review by ruojie0104 — COMMENTED** [review]
thx bro

**Review by fywangVick — APPROVED** [review]

**Review by fywangVick — APPROVED** [review]
ONE MORE TIME

**Review by ruojie0104 — APPROVED** [review]

**Comment by fywangVick** [comment]
Hi !( by Kenny

**Pull request merged**
